harness/ff-android-client-sdk

- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/oksse/SSEListener.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/repository/FeatureRepositoryImpl.java
- examples/example/src/main/java/io/harness/cfsdk/example/MainActivity.kt
Add support to handle target segment events.  When an event is received we make a call to get all evaluations.
When a group rule is changed on the FF server, the SDK receives an event.  The SDK needs to fetch all flag evaluations again as the change to the group could impact what variations a target is served for any given flag.
> [FFM-3838]: Android SDK does not handle target-segment events

- README.md
- cfsdk/build.gradle
- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/AnalyticsPublisherService.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/DefaultMetricsApiFactoryRecipe.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/factories/CloudFactory.java
- examples/GettingStarted/app/build.gradle
**What** 
Adds fix for jsonVariation function which was not returning a JSON object response because it was throwing an exception
**Why**
As per [FFM-4605](https://harness.atlassian.net/browse/FFM-4605) we found the response was double escaped, so we couldn't cast it to a JSON object
Screen showing successful logging of the object, which previously would have just been 'null'
> FFM-4605 - Fix issue where double escaped response was causing exception

- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/utils/GuardObjectWrapper.java
[FFM-4836]: Mitigate potential race condition during the Android SDK intitialization
#What: 
Added GuardObjectWrapper to ensure evaluationPolling.stop() is not called on uninitialized object.
#Why:
To fix potential race condition.
#Testing:
Tested locally by initializing sdk on the emulator.
[FFM-4836]: https://harness.atlassian.net/browse/FFM-4836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-4836]: Mitigate potential race condition during the Android SDK intitialization

- cfsdk/src/main/java/io/harness/cfsdk/cloud/cache/DefaultCache.java
[FFM-5484] Reset cache on init if exception is thrown
What
If we get an exception while loading the initial list of evaluations from the cache then assume cache has gotten corrupt on disk and reset it.
Why
We're seeing type exceptions on the initialize() method on startup which looks to be caused by a corrupt cache on disk. This will remove any bad entries.
Testing
Manual - changed the underlying xml to get it to throw and exception
[FFM-5484]: https://harness.atlassian.net/browse/FFM-5484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-5484] Reset cache on init if exception is thrown

- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/AnalyticsPublisherService.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/SummaryMetrics.java
- In `metricsData` the global target was being used instead of the actual target. This changes the `target` attribute to use the actual target.
- `variationValue` attribute wasn't being sent in `metricsData` - while this didn't have a problem with metrics appearing posting and appearing in the UI, the metrics service asks for this data. This adds the variationValue to the `metricsData` payload.
- Client SDKs should send the actual target
- To honour the metrics API
- Metrics continue to post and appear in the UI.
- Debugged the application and saw that the actual target was in the metrics payload
> FFM-6156 Sent actual target in metrics

- README.md
- cfsdk/build.gradle
- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/AnalyticsPublisherService.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/DefaultMetricsApiFactoryRecipe.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/factories/CloudFactory.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/oksse/RealServerSentEvent.java
- cfsdk/src/main/java/io/harness/cfsdk/logging/CfLogStrategyDefault.java
- cfsdk/src/test/java/android/util/Base64.java
- cfsdk/src/test/java/io/harness/cfsdk/CfClientTest.java
- cfsdk/src/test/java/io/harness/cfsdk/TestUtils.java
- cfsdk/src/test/java/io/harness/cfsdk/mock/MockedCache.java
- cfsdk/src/test/java/io/harness/cfsdk/utils/EventsListenerCounter.java
- examples/GettingStarted/app/build.gradle
- examples/GettingStarted/settings.gradle
FFM-6144 - Android SDK Type casting
Adds additional hardening to event payloads + add new unit tests for CfClient. Also fixes an issue in RealServerSentEvent where if readUtf8Line() returned null on the SSE socket then the CPU would spin in a tight loop.
Testing
New unit tests + manual testing
> FFM-6144 - Android SDK Type casting

- cfsdk/src/main/java/io/harness/cfsdk/CfConfiguration.java
- cfsdk/src/test/java/io/harness/cfsdk/CfClientTest.java
FFM-4603 - Have to manually specify streamURL for the Android SDK
What
Deprecate stream url and drive stream endpoint from base url.
Why
We should remain consistent with other SDKs
Testing
Added new unit tests to check stream endpoint connects when streamUrl is not given
> FFM-4603 - Have to manually specify streamURL for the Android SDK

- cfsdk/build.gradle
- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/Cloud.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/AnalyticsPublisherService.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/DefaultMetricsApiFactoryRecipe.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/factories/CloudFactory.java
- examples/GettingStarted/app/build.gradle
FFM-6396 - Android/Flutter SDK: Can't initialise SDK without Target Identifier
What
Validate and check target for null or empty identifiers and set to name. If neither name or id are given and set to some default values. SDK hangs if it gets a 403 back on auth and doesn't report any error in the logs - so check for authentication failures and throw an exception instead of continuing
Why
Passing in a null identifier in the target causes auth endpoint to fail and return 403, which internally sets authInfo to null
Testing
Tested manually with GettingStarted example
> FFM-6396 - Android/Flutter SDK: Can't initialise SDK without Target Identifier

- cfsdk/build.gradle
- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- examples/GettingStarted/app/build.gradle
Yesterday we added two exception handling paths for
- IllegalArgumentException if user doesn't supply a target ID or name
- APIException is client authentication fails
This change adds return statements to both, so we don't invoke the callback again which results in an exception which crashes the user's app.
So we don't attempt to invoke the callback after already invoking it in an exception path
Manual
> FFM-6395 Return early if authentication or empty target ID encountered

- cfsdk/build.gradle
- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/oksse/OkSse.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/oksse/RealServerSentEvent.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/oksse/SSEListener.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/oksse/ServerSentEvent.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/oksse/model/StatusEvent.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/sse/SSEController.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/sse/SSEControlling.java
- cfsdk/src/test/java/io/harness/cfsdk/CfClientTest.java
- cfsdk/src/test/java/io/harness/cfsdk/mock/MockedSSEController.java
- cfsdk/src/test/java/io/harness/cfsdk/utils/EventsListenerCounter.java
- docs/further_reading.md
- examples/GettingStarted/app/build.gradle
- examples/GettingStarted/app/src/main/java/io/harness/cfsdk/gettingstarted/MainActivity.kt
- examples/GettingStarted/settings.gradle
- examples/example/build.gradle
Previously If an application lost internet connectivity and during that period new events were streamed but missed; upon reconnecting the SDK would not get stream the latest events. This would result in incorrect flag evaluations as the cache would be out of date. 
This change introduces a new event `SSE_RESUME` which is emitted by the `SSEListener` class if it detects that the SSE service has been started in the context of `reschedule`.  The `CFClient` event listener will act upon the `SSE_RESUME` event by reloading all evaluations from the server and updating all registered `EventListener`s with the change. 
So that a device that has temporarily lost internet connectivity has current evaluations without having to restart the application. 
Manual using an emulator with example …
> FFM-6574 - Stream latest changes upon network reconnect

- cfsdk/build.gradle
- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/Cloud.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/repository/FeatureRepository.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/repository/FeatureRepositoryImpl.java
- cfsdk/src/test/java/io/harness/cfsdk/CfClientTest.java
- cfsdk/src/test/java/io/harness/cfsdk/TestUtils.java
- cfsdk/src/test/java/io/harness/cfsdk/cloud/analytics/AnalyticsManagerTest.java
- cfsdk/src/test/java/io/harness/cfsdk/cloud/repository/FeatureRepositoryImplTest.java
- cfsdk/src/test/java/io/harness/cfsdk/mock/MockedCache.java
- cfsdk/src/test/java/io/harness/cfsdk/mock/MockedCloudFactory.java
- cfsdk/src/test/java/io/harness/cfsdk/mock/MockedNetworkInfoProvider.java
- examples/GettingStarted/app/build.gradle
- examples/GettingStarted/settings.gradle
What
Fix FeatureRepositoryImpl to prefer cache, call out to network to get flag only if its not found in cache and network is available.
Why
The getEvaluation function is performing very poorly and causing excessive API callouts to the ff-server when it should be using the cache.
Testing
Several new unit tests added + manual
> FFM-6713 - Android SDK - Evaluation functions not using cache

- README.md
- docs/dev_environment.md
**Changes**
Fixing a few small readme issues i noticed setting it up
- Link to setup and run emulator was broken
- A couple of the copy paste code terminal commands contained terminal output too and would fail, separating these to make them one click wonders again
- One of the commands to unpack the zip contained an extra /sdk that shouldn't be there because it's already in the $ANDROID_HOME path
> (FFM-7867) Readme fixes

- cfsdk/src/main/java/io/harness/cfsdk/cloud/Cloud.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/DefaultMetricsApiFactoryRecipe.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/oksse/RealServerSentEvent.java
FFM-7037 - Fix HTTP header to use getEnvironmentIdentifier instead of getEnvironment
What
Minor fix to a previous commit use the readable id instead of the hash in the HTTP header
> FFM-7037 - Fix HTTP header to use getEnvironmentIdentifier instead of getEnvironment

- cfsdk/build.gradle
- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/cache/DefaultCache.java
- cfsdk/src/test/java/io/harness/cfsdk/cloud/DefaultCacheTest.java
- cfsdk/src/test/java/io/harness/cfsdk/cloud/analytics/AnalyticsManagerTest.java
[FFM-8630] - Simplify/harden code in DefaultCache
What
Simplify the caching code and remove the thread pool. Also remove the nested map as this isn't threadsafe. Instead use a single ConncurrentHashMap<> and embedd the env inside the map key.
Why
Getting rid of the nested hashmap to reduce the chance of proguard creating code that doesn't work. Also remove potential race conditions and reduce memory footprint. Make the code easier to follow
Testing
New unit test + manual testing
[FFM-8630]: https://harness.atlassian.net/browse/FFM-8630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-8630] - Simplify/harden code in DefaultCache

- cfsdk/build.gradle
- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
Emits the `EVALUATION_RELOADED` event to users on client init, and on each polling interval
So the `EVALUATION_RELOADED` event is fired when evaluations are reloaded
Manual with sample app
> FFM-9445 Emit `EVALUATION_RELOADED` on polling intervals

- build.gradle
[FFM-9500] - Set scanBuildEnv to off
What
Remove scanBuildEnv as its bringing in more JARs than we need to scan.
Why
We're seeing a lot of false-positives reported in STO that relate to build artifacts
[FFM-9500]: https://harness.atlassian.net/browse/FFM-9500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9500] - Set scanBuildEnv to off

- build.gradle
- cfsdk/build.gradle
[FFM-9531] - CVE-2021-0341 okhttp dependency to 4.11.0
What
Bump okhttp version from 4.9.0 to 4.11.0
Why
Removes several CVEs including kotlin-stdlib 1.4.10 and okio 2.8.0
Testing
Manual
[FFM-9531]: https://harness.atlassian.net/browse/FFM-9531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9531] - CVE-2021-0341 okhttp dependency

- cfsdk/build.gradle
- cfsdk/src/main/java/io/harness/cfsdk/cloud/core/client/JSON.java
[FFM-9530] - CVE-2022-25647 update gson dependency
What
Update gson dependency to latest. Also remove gson-fire as it hasn't been seen a release in several years and we don't seem to use it.
Why
gson-fire is bringing in an older version of gson which has a CVE against it.
Testing
Manual
[FFM-9530]: https://harness.atlassian.net/browse/FFM-9530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9530] - CVE-2022-25647 update gson dependency

- cfsdk/build.gradle
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/test/java/io/harness/cfsdk/CfClientTest.java
What
Fix input to JSONObject and remove unneeded Apache dependency
Why
There’s a bug in how we parse the JSON returned to jsonVariation. Before passing to JSONObject we strip off the surrounding braces which causes an exception to be thrown
E/CfClient: Value flag of type java.lang.String cannot be converted to JSONObject
org.json.JSONException: Value flag of type java.lang.String cannot be converted to JSONObject
at org.json.JSON.typeMismatch(JSON.java:111)
at org.json.JSONObject.<init>(JSONObject.java:163)
at org.json.JSONObject.<init>(JSONObject.java:176)
at io.harness.cfsdk.CfClient.jsonVariation(CfClient.java:872)
at com.example.android_sdk_test.MainActivity.lambda$onCreate$2(MainActivity.java:146)
at com.example.android_sdk_test.MainActivity.$r8$lambda$yX3gDMwxpCIvBmOil3jvG5PQc7c(Unkn …
> [FFM-9598] -  jsonVariation always returns default value

- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/AnalyticsPublisherService.java
- cfsdk/src/test/java/io/harness/cfsdk/cloud/analytics/AnalyticsPublisherServiceTest.java
[FFM-9347] - Avoid posting metrics if total evaluation count is 0
What
If total sum of evaluations is equal to zero then skip sending the metrics payload this iteration.
Why
We're seeing payloads with 0 counts on the backend. We want to avoid wasting bandwidth.
Testing
New unit test
[FFM-9347]: https://harness.atlassian.net/browse/FFM-9347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9347] - Avoid posting metrics if total evaluation count is 0

- cfsdk/src/main/java/io/harness/cfsdk/cloud/factories/CloudFactory.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/network/NewRetryInterceptor.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/sse/EventSource.java
- cfsdk/src/test/java/io/harness/cfsdk/CfClientTest.java
[FFM-8526] - Add retry interceptor to authentication
What
Enable the retry interceptor so authentication requests can be retried several times (with a random interval)
Why
Add more network resilience so we don't immediately bail out when a transient network error happens.
Testing
Unit tests + manual
[FFM-8526]: https://harness.atlassian.net/browse/FFM-8526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-8526] - Add retry interceptor to authentication

- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/common/SdkCodes.java
- cfsdk/src/test/java/io/harness/cfsdk/common/SdkCodesTest.java
[FFM-9559] - Add waitForInitialization()
What
Adds waitForInitialization() and waitForInitialization(timeoutMs)
Why
We want to be consistent with other SDKs and give threads the ability to wait for SDKs to fully authenticate and populate their cache
Testing
Manual
[FFM-9559]: https://harness.atlassian.net/browse/FFM-9559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9559] - Add waitForInitialization()

- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/sse/EventSource.java
[FFM-8529] - Fix SSE re-connect from previous commit
What
Previous commit threw an exception killing the main activity thread, instead we only want to send an SSE_END event to get the SDK to run reschedule()
Why
Java SDK has different exception handling to Android
Testing
Manual
[FFM-8529]: https://harness.atlassian.net/browse/FFM-8529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-8529] - Fix SSE re-connect from previous commit

- README.md
- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- examples/GettingStarted/app/build.gradle
- examples/GettingStarted/app/src/main/java/io/harness/cfsdk/gettingstarted/MainActivity.kt
When a flag is toggled while the device is offline, when the device comes back online and gets notified of the change, it can take a few attempts for it to pull the latest evaluation back from the client service. The problem is the method relied on mutating the original callback `statusEvent` parameter, and then it emitted it at the end with its final mutated state. However, because the fetch call from the client service is happens concurrently, the `statusEvent` variable might not get mutated in time, and we’d emit the original event which comes through as a List<Evaluation> . 
This PR tidied up the `eventsListener` method to
- No longer mutate the callback `statusEvent` 
- Create a new `StatusEvent` for each event type, and emit it directly there. 
It also:
- Does not mutate evaluation …
> FFM-9941 Fix incorrect event orchestration

- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/test/java/io/harness/cfsdk/CfClientTest.java
If a default variation was returned, for example if a nonexistent flag was evaluated against, then the SDK would crash on an unchecked `ClassCastException` when trying to cast the user supplied default value to string. The method responsible was `getEvaluationById` and the default value could be `bool`, `double`, `string`, or `JSONObject` so this was not a valid approach.
- `getEvaluationID` now returns `null` in cases where it can't return an `Evaluation` and responsibility is delegated to the variation methods to check for null and safely return the defaults. No casting is required here.
- `jsonVariation` now actually returns the default variation, instead of a json object with flagID + null as the KV.
-  No longer post metrics if an evaluation fails
- Refactored `getEvaluatoinById` and …
> FFM-10297 Fix handling of default variations

- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- examples/GettingStarted/app/build.gradle
If initialization failed, an exception was thrown from within the thread pool which could not be caught by the try-catch that was used outside of it it. This caused an uncaught exception to crash the thread and user application. 
This change returns an auth result, instead of throwing an exception. This was used over a `Future` which is a blocking call.
Manual, sample application.
> FFM-10359 Fix uncaught exception if initialization fails

- cfsdk/publish-mavencentral.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/sse/EventSource.java
**What**
This is a minimum fix to get rid of a null pointer exception that can happen. First approach was to make `cloud` final to guarantee it can never be null however `getInstance()` prevents us from doing that since it controls the instance creation. Second approach was to move `this.cloud = cloudFactory.cloud()` before init thread creation however this results in a `NetworkOnMainThreadException`.
For now adding a simple null check but the proper fix is to refactor the code into worker threads and avoid assigning class members from different threads.
Plus:
- Fix a problem where SDK would not reconnect when started with no network
- Remove duplicate SSE event log
**Why**
See seeing a race condition between the init and reschedule when an SDK is started with no network
**Testing** …
> [FFM-10477] - Fix null pointer when calling initialize()

- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/SdkThread.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/AnalyticsPublisherService.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/network/NewRetryInterceptor.java
- cfsdk/src/test/java/io/harness/cfsdk/cloud/network/NewRetryInterceptorTest.java
- examples/tlsexample/src/main/res/xml/network_security_config.xml
- settings.gradle
**What**
If Retry-After header is detected, use that first when retrying a failed API connection
**Why**
Allow backend to control when SDKs retry
**Testing**
Manual + unit testing
> [FFM-10745] - Add support for Retry-After header

- cfsdk/src/main/java/io/harness/cfsdk/SdkThread.java
**What**
Only create one instance of NetworkInfoProvider
**Why**
We are seeing the following exception reported:
```
Fatal Exception: android.net.ConnectivityManager$TooManyRequestsException:
at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4202)
at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4394)
at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4923)
at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4890)
at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4864)
at io.harness.cfsdk.cloud.network.NetworkInfoProvider.<init>(NetworkInfoProvider.java:27)
at …
```
> [FFM-10879] - Fix TooManyRequestsException error

- README.md
- build.gradle
- cfsdk/build.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/Client.java
- cfsdk/src/main/java/io/harness/cfsdk/SdkThread.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/events/AuthCallback.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/events/AuthResult.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/network/NetworkInfoProviding.java
- cfsdk/src/test/java/io/harness/cfsdk/CfClientTest.java
- docs/further_reading.md
- settings.gradle
**What**
Upgrade okhttp from 4.11.0 to 4.12.0
Java doc updates
Minor fixes
**Why**
Reports of the following CVE (gzip vulnerability) due to an old version of okio-jvm being brought in by okhttp
`okio-jvm-3.2.0.jar (pkg:maven/com.squareup.okio/okio-jvm@3.2.0, cpe:2.3:a:squareup:okio:3.2.0:*:*:*:*:*:*:*) : CVE-2023-3635`
**Testing**
Manual
> [FFM-10903] - CVE-2023-3635: update okhttp/okio-jvm

- README.md
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfConfiguration.java
- cfsdk/src/main/java/io/harness/cfsdk/SdkThread.java
- cfsdk/src/test/java/io/harness/cfsdk/CfConfigurationTest.java
- docs/further_reading.md
- examples/GettingStarted/src/main/java/io/harness/cfsdk/gettingstarted/MainActivity.kt
- settings.gradle
- Implements `pollingEnabled` configuration option:
- Thread model has been tweaked so that we break from the main sdk thread if streaming and polling are both disabled
- Fixes 
- `AuthCallback` success result only returned once. Fail results continue to be returned as many times as required, up until the SDK initializes sucesfully for the first time.  If the sdk thread aborts after it has initialized sucesfully, and re-auth is attempted, the success and fail result will no longer be returned. 
- If a user attempts to register an event listener at the same time an event has came in in another listener, then a `ConcurrentModificationException` could occur.  This could especially happen prior to the above `AuthCallback` fix, when a user registered their listener in the callback scope.  We …
> FFM-10940 Enable no polling mode + bug fixes

- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/network/NetworkInfoProviding.java
- settings.gradle
We are seeing `ConcurrentModificationException` due to modifying a `ConcurrentHashSet` while iterating.  This may be similar to an issue we fixed in https://github.com/harness/ff-android-client-sdk/pull/95/files line 427. 
The fix here is to use a `CopyOnWriteArraySet` which in effect is similar to the fix we applied in the above PR.  Considering there are lots of iterations in the affected class, it seems cleaner to use this set instead of manually copying the `ConcurrentHashSet` before iterating it.
I have not been able to reproduce the issue, but the `CopyOnWriteArraySet` allows modification of the set while it is being iterated.
> FFM-11122 Use CopyOnWriteArraySet

- cfsdk/build.gradle
[FFM-11223] - Fix CVE-2024-23081 (threeten)
**What**
Update threeten library to 1.6.9
**Why**
STO is reporting the following vulnerability https://www.cve.org/CVERecord?id=CVE-2024-23081 and breaking the build
**Testing**
Testing will be rolled into FFM-11216
[FFM-11223]: https://harness.atlassian.net/browse/FFM-11223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-11223] - Fix CVE-2024-23081 (threeten)

- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/Client.java
- cfsdk/src/main/java/io/harness/cfsdk/SdkThread.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/AnalyticsManager.java
- cfsdk/src/main/java/io/harness/cfsdk/common/SdkCodes.java
- cfsdk/src/test/java/io/harness/cfsdk/common/SdkCodesTest.java
- settings.gradle
To resolve a Flutter SDK issue https://github.com/harness/ff-flutter-client-sdk/issues/37 
- adds an async method to close the SDK, which returns a `Future` on completion. 
- synchronizes the `initialize` and `close` methods with a lock 
Also adds the SDK Codes `3xxx` for closing the SDK
Manual - getting started sample app and Flutter SDK sample app
> FFM-11625 Add future based `close()` method

- cfsdk/build.gradle
- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/SdkThread.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/cache/DefaultCache.java
- cfsdk/src/test/java/io/harness/cfsdk/CfClientTest.java
- cfsdk/src/test/java/io/harness/cfsdk/cloud/DefaultCacheTest.java
- docs/further_reading.md
- settings.gradle
- V2 of this SDK did not remove an unused `InternalCache` implementation which is backed by the `Hawk` library.  This cache was not utilised in V1, and should not have made it into V2.  Additionaly, this cache was adding significant latency to init times, because of the new thread model in V2. 
- Fixes a bug where if the callback is used to initialise and the device is currently offline, then no callback will be emitted until the device comes online and gets an init result.
- Manual: 
-  all evaluations still cached in memory:
- on init
- when streamed
- when polled 
-  init latency times are back to expected levels
- New unit test for client init flow
> FFM-11750 Remove unused internal cache implementation

- cfsdk/src/main/java/io/harness/cfsdk/AndroidSdkVersion.java
- cfsdk/src/main/java/io/harness/cfsdk/CfClient.java
- cfsdk/src/main/java/io/harness/cfsdk/SdkThread.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/analytics/AnalyticsManager.java
- cfsdk/src/main/java/io/harness/cfsdk/cloud/network/NewRetryInterceptor.java
- settings.gradle
When `client.Close()` or `client.CloseWithFuture()` was called, the `Main SDK Thread` did not handle `InterruptedException` correctly because they were getting swallowed by the main capturing of `Runnable` exceptions. In that case, the `Runnable` being caught would mean the SDK would sleep for a minute and retry. 
This fix ensures that the: 
- The `Run` method catches InterruptedExceptions and breaks the `Main SDK Thread`.
- The http `Interceptor` which is used for http requests throws InterruptedException for any in-flight requests, mainly streaming which is long-lived, but also for authentication and polling. Before these would have retried.  These come through as `APIException` but the `cause` is obtained and checked. 
Also fixes unrelated bug where if the API key was null or empty, …
> FFM-11779 Fix SDK Client Not Closing Correctly
